[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://pxtakrpkzzpbrlbkykav.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4dGFrcnBrenpwYnJsYmt5a2F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NjM3MzEsImV4cCI6MjA1ODIzOTczMX0.r5B4VrR4kHOIcJ-FFlqhvUg0P3pi2i9HDAZ9U1xpqp0"

# Handle Next.js routing
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/_next/static/:splat"
  status = 200
  force = true
  conditions = {Path = "/_next/static/*"}

[[redirects]]
  from = "/*"
  to = "/api/:splat"
  status = 200
  force = true
  conditions = {Path = "/api/*"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200